# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('short', models.CharField(max_length=20)),
                ('hours', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
